# Generated by Django 5.1.2 on 2025-07-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_delete_samplemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('business', 'ビジネス'), ('life', '生活'), ('literature', '文学'), ('other', 'その他')], max_length=100),
        ),
    ]
